version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: verbalyst-api
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - verbalyst-net

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        NGINX_ENV: ${NGINX_ENV}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: verbalyst-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - verbalyst-net
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

networks:
  verbalyst-net:
    driver: bridge
