services:
  db:
      image: postgres:17
      container_name: verbalyst_db
      restart: unless-stopped
      env_file: .env
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - verbalyst_pgdata:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      networks:
        - verbalyst-net
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: verbalyst-api
    restart: unless-stopped
    env_file: backend/.env
    expose:
      - "8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - verbalyst-net

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
      args:
        NGINX_ENV: ${NGINX_ENV}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: verbalyst-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - verbalyst-net
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

volumes:
  verbalyst_pgdata:

networks:
  verbalyst-net:
    driver: bridge
