"""initial migration setup

Revision ID: ea4c1ae49824
Revises: 
Create Date: 2025-05-14 02:48:06.396998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea4c1ae49824'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_provider', sa.String(), nullable=False),
    sa.Column('auth_sub', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('total_games', sa.Integer(), nullable=False),
    sa.Column('total_wins', sa.Integer(), nullable=False),
    sa.Column('total_hints_used', sa.Integer(), nullable=False),
    sa.Column('total_guesses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_auth_sub'), 'profile', ['auth_sub'], unique=True)
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=True)
    op.create_table('distance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_word', sa.Integer(), nullable=False),
    sa.Column('fk_target', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fk_target'], ['word.id'], ),
    sa.ForeignKeyConstraint(['fk_word'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_target_word', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_target_word'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('fk_game_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_code'), 'room', ['code'], unique=True)
    op.create_table('hint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_target', sa.Integer(), nullable=False),
    sa.Column('fk_word', sa.Integer(), nullable=False),
    sa.Column('fk_room_id', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fk_room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['fk_target'], ['word.id'], ),
    sa.ForeignKeyConstraint(['fk_word'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_room_id', sa.Integer(), nullable=False),
    sa.Column('fk_profile_id', sa.Integer(), nullable=False),
    sa.Column('hints_used', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=False),
    sa.Column('guesses_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fk_profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['fk_room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_player_id', sa.Integer(), nullable=False),
    sa.Column('fk_room_id', sa.Integer(), nullable=True),
    sa.Column('guess', sa.String(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('x', sa.Float(), nullable=False),
    sa.Column('y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['fk_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['fk_room_id'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guess')
    op.drop_table('player')
    op.drop_table('hint')
    op.drop_index(op.f('ix_room_code'), table_name='room')
    op.drop_table('room')
    op.drop_table('game')
    op.drop_table('distance')
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_profile_auth_sub'), table_name='profile')
    op.drop_table('profile')
    # ### end Alembic commands ###
